apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: REPLACE_WITH_ACM_CERTIFICATE_ARN

  annotations:spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /posts(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: posts
                port:
                  number: 8001
          - path: /comments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments
                port:
                  number: 8002
          - path: /query(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: query
                port:
                  number: 8003
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client
                port:
                  number: 80
