name: CD Pipeline
on:
  push:
    branches: [dev]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Build Push and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [posts, comments, query, event-bus, moderation, client]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::657830185735:role/github-actions-oidc-role
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/microservices-demo-${{ matrix.service }}:latest \
            ./${{ matrix.service }}
          docker push $ECR_REGISTRY/microservices-demo-${{ matrix.service }}:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
           --name microservices-demo \
           --region us-east-1

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment/${{ matrix.service }} \
            --namespace microservices-demo
